services:
  rococo-db:
    container_name: rococo-db
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306
    networks:
      - rococo-network
    dns_search: .

  auth.rococo.dc:
    container_name: auth.rococo.dc
    image: dtuchs/rococo-auth:latest
    ports:
      - 9000:9000
    restart: always
    depends_on:
      rococo-db:
        condition: service_started
    networks:
      - rococo-network
    dns_search: .

  api.rococo.dc:
    container_name: api.rococo.dc
    image: dtuchs/rococo-api:latest
    ports:
      - 8080:8080
    restart: always
    depends_on:
      auth.rococo.dc:
        condition: service_started
    networks:
      - rococo-network
    dns_search: .

  client.rococo.dc:
    container_name: client.rococo.dc
    image: dtuchs/rococo-client:latest
    build:
      context: ./rococo-client
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      api.rococo.dc:
        condition: service_started
    networks:
      - rococo-network

  rococo-e2e:
    container_name: rococo-e2e
    image: dtuchs/rococo-e2e:latest
    build:
      context: ./
      dockerfile: ./rococo-e2e/Dockerfile
      args:
        ALLURE_DOCKER_API: ${ALLURE_DOCKER_API}
        BUILD_URL: ${BUILD_URL}
        HEAD_COMMIT_MESSAGE: ${HEAD_COMMIT_MESSAGE}
        EXECUTION_TYPE: ${EXECUTION_TYPE}
    environment:
      ALLURE_DOCKER_API: ${ALLURE_DOCKER_API}
      BUILD_URL: ${BUILD_URL}
      HEAD_COMMIT_MESSAGE: ${HEAD_COMMIT_MESSAGE}
      EXECUTION_TYPE: ${EXECUTION_TYPE}
    depends_on:
      client.rococo.dc:
        condition: service_started
    networks:
      - rococo-network

  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:1.11.2
    platform: linux/${ARCH}
    volumes:
      - ./selenoid:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: [ "-conf", "/etc/selenoid/browsers.json", "-limit", "2", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "heisenbug-2023-autumn_rococo-network" ]
    ports:
      - 4444:4444
    networks:
      - rococo-network

networks:
  rococo-network:
    driver: bridge
