services:
  rococo-db:
    container_name: rococo-db
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    networks:
      - rococo-network
    dns_search: .

  auth.rococo.dc:
    container_name: auth.rococo.dc
    image: ${PREFIX}/rococo-auth-${PROFILE}:latest
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      rococo-db:
        condition: service_healthy
    networks:
      - rococo-network
    dns_search: .

  api.rococo.dc:
    container_name: api.rococo.dc
    image: ${PREFIX}/rococo-api-${PROFILE}:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      auth.rococo.dc:
        condition: service_started
    networks:
      - rococo-network
    dns_search: .

  client.rococo.dc:
    container_name: client.rococo.dc
    image: ${PREFIX}/rococo-client-${PROFILE}:latest
    ports:
      - "81:81"
    restart: always
    depends_on:
      api.rococo.dc:
        condition: service_started
    networks:
      - rococo-network
    dns_search: .

  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:1.11.2
    volumes:
      - ./selenoid:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: [ "-conf", "/etc/selenoid/browsers.json", "-limit", "3", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "heisenbug-2023-autumn_rococo-network" ]
    ports:
      - "4444:4444"
    networks:
      - test-network
    dns_search: .

  rococo-e2e:
    container_name: rococo-e2e
    image: ${PREFIX}/rococo-e2e:latest
    environment:
      - ALLURE_DOCKER_API=${ALLURE_DOCKER_API}
    depends_on:
      client.rococo.dc:
        condition: service_started
    networks:
      - rococo-network
    dns_search: .

networks:
  rococo-network:
    driver: bridge
