server:
  port: 9000

spring:
  application:
    name: rococo-auth
  mvc:
    log-request-details: true
  datasource:
    username: root
    password: secret
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    generate-ddl: true
    open-in-view: false
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

oauth2:
  client-id: client
  client-secret: '{noop}secret'

---
spring:
  config:
    activate:
      on-profile: 'local'

  datasource:
    url: jdbc:mysql://localhost:3306/rococo-auth?serverTimezone=UTC&createDatabaseIfNotExist=true

rococo-ui:
  uri: http://127.0.0.1:3000
rococo-auth:
  uri: http://127.0.0.1:9000
---
spring:
  config:
    activate:
      on-profile: 'docker'

  datasource:
    url: jdbc:mysql://rococo-db:3306/rococo-auth?serverTimezone=UTC&createDatabaseIfNotExist=true

rococo-ui:
  uri: http://client.rococo.dc
rococo-auth:
  uri: http://auth.rococo.dc:9000
---
