name: api-stage
on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/api-stage.yaml'
      - 'rococo-api/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push required props to GITHUB_ENV
        run: |
          echo "PROFILE=stage" >> $GITHUB_ENV

      - name: Docker login
        run: |
          docker login --username dtuchs --password "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: Deploy api
        working-directory: ./
        run: |
          pwd
          gradle :rococo-api:jib -x :rococo-e2e:test
          docker compose pull api.rococo.dc
          docker compose stop api.rococo.dc && docker compose up -d --no-deps api.rococo.dc
          docker system prune -a -f
          echo "Deploy api to stage done!"
