name: auth-stage
on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/auth-stage.yaml'
      - 'rococo-auth/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push required props to GITHUB_ENV
        run: |
          echo "PROFILE=stage" >> $GITHUB_ENV
          echo "PREFIX=dtuchs" >> $GITHUB_ENV

      - name: Docker login
        run: |
          docker login --username ${{ vars.DOCKER_HUB_ACC }} --password "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: Deploy auth
        working-directory: ./
        run: |
          pwd
          gradle :rococo-auth:jib -x :rococo-e2e:test
          docker compose pull auth.rococo.dc
          docker compose stop auth.rococo.dc && docker compose up -d --no-deps auth.rococo.dc
          docker system prune -a -f
          echo "Deploy auth to stage done!"
