name: client-stage
on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/client-stage.yaml'
      - 'rococo-client/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push required props to GITHUB_ENV
        run: |
          echo "PROFILE=stage" >> $GITHUB_ENV

      - name: Docker login
        run: |
          docker login --username dtuchs --password "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: Build frontend & deploy to stage
        working-directory: ./rococo-client
        run: |
          pwd
          docker build --build-arg PROFILE=${{ env.PROFILE }} -t dtuchs/rococo-client-${{ env.PROFILE }}:0.0.1-SNAPSHOT -t dtuchs/rococo-client-${{ env.PROFILE }}:latest .
          docker push dtuchs/rococo-client-${{ env.PROFILE }}:0.0.1-SNAPSHOT
          docker push dtuchs/rococo-client-${{ env.PROFILE }}:latest
          cd ../ || exit 1
          docker compose pull client.rococo.dc
          docker compose stop client.rococo.dc && docker compose up -d --no-deps client.rococo.dc
          docker system prune -a -f
          echo "Deploy frontend to stage done!"
